const PRODUCTS = [
  {
    id: "l-001",
    name: "AeroBook 14 Pro",
    type: "laptop",
    cpuBrand: "intel",
    cpu: "Intel Core i7-1360P",
    ram: 16,
    storage: 512,
    gpuBrand: "integrated",
    gpu: "Intel Iris Xe",
    screen: 14,
    price: 1099,
    tags: ["ultrabook", "lightweight", "usb-c", "intel"],
    url: "#"
  },
  {
    id: "l-002",
    name: "GamerX 16 RTX",
    type: "laptop",
    cpuBrand: "intel",
    cpu: "Intel Core i7-14700H",
    ram: 32,
    storage: 1024,
    gpuBrand: "nvidia",
    gpu: "NVIDIA RTX 4060",
    screen: 16,
    price: 1599,
    tags: ["gaming", "rtx", "144hz", "rgb"],
    url: "#"
  },
  {
    id: "l-003",
    name: "Creator 15 Studio",
    type: "laptop",
    cpuBrand: "intel",
    cpu: "Intel Core i9-13900H",
    ram: 32,
    storage: 2048,
    gpuBrand: "nvidia",
    gpu: "NVIDIA RTX 4070",
    screen: 15.6,
    price: 2399,
    tags: ["creator", "4k", "color-accurate"],
    url: "#"
  },
  {
    id: "l-004",
    name: "Swift 13 Air",
    type: "laptop",
    cpuBrand: "amd",
    cpu: "AMD Ryzen 7 7840U",
    ram: 16,
    storage: 512,
    gpuBrand: "integrated",
    gpu: "Radeon 780M",
    screen: 13.3,
    price: 999,
    tags: ["portable", "usb-c", "long-battery"],
    url: "#"
  },
  {
    id: "l-005",
    name: "MacBook Pro 14",
    type: "laptop",
    cpuBrand: "apple",
    cpu: "Apple M3 Pro",
    ram: 18,
    storage: 1024,
    gpuBrand: "apple",
    gpu: "Apple GPU",
    screen: 14.2,
    price: 2399,
    tags: ["macos", "retina", "creator"],
    url: "#"
  },
  {
    id: "d-001",
    name: "Atlas Tower",
    type: "desktop",
    cpuBrand: "amd",
    cpu: "AMD Ryzen 7 7800X3D",
    ram: 32,
    storage: 2048,
    gpuBrand: "nvidia",
    gpu: "NVIDIA RTX 4080",
    screen: 0,
    price: 2499,
    tags: ["gaming", "desktop", "liquid-cool"],
    url: "#"
  },
  {
    id: "d-002",
    name: "OfficeCore SFF",
    type: "desktop",
    cpuBrand: "intel",
    cpu: "Intel Core i5-13400",
    ram: 16,
    storage: 512,
    gpuBrand: "integrated",
    gpu: "Intel UHD",
    screen: 0,
    price: 699,
    tags: ["office", "compact", "quiet"],
    url: "#"
  },
  {
    id: "m-001",
    name: "NanoBox Mini",
    type: "mini-pc",
    cpuBrand: "amd",
    cpu: "AMD Ryzen 5 6600H",
    ram: 16,
    storage: 512,
    gpuBrand: "integrated",
    gpu: "Radeon 660M",
    screen: 0,
    price: 499,
    tags: ["mini", "htpc", "usb-c"],
    url: "#"
  },
  {
    id: "a-001",
    name: "AllView 24",
    type: "all-in-one",
    cpuBrand: "intel",
    cpu: "Intel Core i7-1355U",
    ram: 16,
    storage: 1024,
    gpuBrand: "integrated",
    gpu: "Intel Iris Xe",
    screen: 23.8,
    price: 1199,
    tags: ["aio", "office", "touch"],
    url: "#"
  }
];
