import prisma from "../src/lib/prisma.js";

const products = [
  {
    name: "AeroBook 14 Pro",
    brand: "Aero",
    type: "laptop",
    cpuBrand: "intel",
    cpu: "Intel Core i7-1360P",
    ram: 16,
    storage: 512,
    gpuBrand: "integrated",
    gpu: "Intel Iris Xe",
    screen: 14,
    price: 1099,
    availability: "in_stock",
    imageUrl: "/images/placeholder.svg",
    tags: ["ultrabook", "lightweight", "usb-c", "intel"],
    url: "#"
  },
  {
    name: "GamerX 16 RTX",
    brand: "GamerX",
    description: "Gaming laptop with RTX graphics and high refresh display.",
    category: "gaming",
    type: "laptop",
    cpuBrand: "intel",
    cpu: "Intel Core i7-14700H",
    ram: 32,
    storage: 1024,
    gpuBrand: "nvidia",
    gpu: "NVIDIA RTX 4060",
    screen: 16,
    price: 1599,
    availability: "in_stock",
    rating: 4.6,
    popularity: 820,
    imageUrl: "/images/placeholder.svg",
    tags: ["gaming", "rtx", "144hz", "rgb"],
    url: "#"
  },
  {
    name: "Creator 15 Studio",
    brand: "Creator",
    description: "Creator-focused laptop with high-end CPU/GPU and large SSD.",
    category: "computers",
    type: "laptop",
    cpuBrand: "intel",
    cpu: "Intel Core i9-13900H",
    ram: 32,
    storage: 2048,
    gpuBrand: "nvidia",
    gpu: "NVIDIA RTX 4070",
    screen: 15.6,
    price: 2399,
    availability: "preorder",
    rating: 4.7,
    popularity: 410,
    inStock: false,
    imageUrl: "/images/placeholder.svg",
    tags: ["creator", "4k", "color-accurate"],
    url: "#"
  },
  {
    name: "Swift 13 Air",
    brand: "Swift",
    type: "laptop",
    cpuBrand: "amd",
    cpu: "AMD Ryzen 7 7840U",
    ram: 16,
    storage: 512,
    gpuBrand: "integrated",
    gpu: "Radeon 780M",
    screen: 13.3,
    price: 999,
    availability: "in_stock",
    imageUrl: "/images/placeholder.svg",
    tags: ["portable", "usb-c", "long-battery"],
    url: "#"
  },
  {
    name: "MacBook Pro 14",
    brand: "Apple",
    type: "laptop",
    cpuBrand: "apple",
    cpu: "Apple M3 Pro",
    ram: 18,
    storage: 1024,
    gpuBrand: "apple",
    gpu: "Apple GPU",
    screen: 14.2,
    price: 2399,
    availability: "in_stock",
    imageUrl: "/images/placeholder.svg",
    tags: ["macos", "retina", "creator"],
    url: "#"
  },
  {
    name: "Atlas Tower",
    brand: "Atlas",
    description: "High-performance desktop tower for gaming and creators.",
    category: "gaming",
    type: "desktop",
    cpuBrand: "amd",
    cpu: "AMD Ryzen 7 7800X3D",
    ram: 32,
    storage: 2048,
    gpuBrand: "nvidia",
    gpu: "NVIDIA RTX 4080",
    screen: 0,
    price: 2499,
    availability: "in_stock",
    rating: 4.8,
    popularity: 560,
    imageUrl: "/images/placeholder.svg",
    tags: ["gaming", "desktop", "liquid-cool"],
    url: "#"
  },
  {
    name: "OfficeCore SFF",
    brand: "OfficeCore",
    description: "Compact office desktop for everyday productivity.",
    category: "office",
    type: "desktop",
    cpuBrand: "intel",
    cpu: "Intel Core i5-13400",
    ram: 16,
    storage: 512,
    gpuBrand: "integrated",
    gpu: "Intel UHD",
    screen: 0,
    price: 699,
    availability: "in_stock",
    rating: 4.2,
    popularity: 300,
    imageUrl: "/images/placeholder.svg",
    tags: ["office", "compact", "quiet"],
    url: "#"
  },
  {
    name: "NanoBox Mini",
    brand: "NanoBox",
    type: "mini-pc",
    cpuBrand: "amd",
    cpu: "AMD Ryzen 5 6600H",
    ram: 16,
    storage: 512,
    gpuBrand: "integrated",
    gpu: "Radeon 660M",
    screen: 0,
    price: 499,
    availability: "in_stock",
    imageUrl: "/images/placeholder.svg",
    tags: ["mini", "htpc", "usb-c"],
    url: "#"
  },
  {
    name: "AllView 24",
    brand: "AllView",
    description: "All-in-one desktop with 24-inch display for office use.",
    category: "office",
    type: "all-in-one",
    cpuBrand: "intel",
    cpu: "Intel Core i7-1355U",
    ram: 16,
    storage: 1024,
    gpuBrand: "integrated",
    gpu: "Intel Iris Xe",
    screen: 23.8,
    price: 1199,
    availability: "in_stock",
    rating: 4.3,
    popularity: 260,
    imageUrl: "/images/placeholder.svg",
    tags: ["aio", "office", "touch"],
    url: "#"
  },
  {
    name: "Lenovo ThinkPad E14",
    brand: "Lenovo",
    type: "laptop",
    cpuBrand: "intel",
    cpu: "Intel Core i5-1335U",
    ram: 16,
    storage: 512,
    gpuBrand: "integrated",
    gpu: "Intel Iris Xe",
    screen: 14,
    price: 899,
    availability: "in_stock",
    imageUrl: "/images/placeholder.svg",
    tags: ["lenovo", "business", "thinkpad"],
    url: "#"
  },
  {
    name: "Lenovo Legion 5",
    brand: "Lenovo",
    description: "Gaming laptop with RTX graphics and fast SSD.",
    category: "gaming",
    type: "laptop",
    cpuBrand: "amd",
    cpu: "AMD Ryzen 7 7735H",
    ram: 16,
    storage: 1024,
    gpuBrand: "nvidia",
    gpu: "NVIDIA RTX 4060",
    screen: 15.6,
    price: 1399,
    availability: "in_stock",
    rating: 4.5,
    popularity: 640,
    imageUrl: "/images/placeholder.svg",
    tags: ["lenovo", "gaming", "144hz"],
    url: "#"
  },
  {
    name: "Dell XPS 13 Plus",
    brand: "Dell",
    type: "laptop",
    cpuBrand: "intel",
    cpu: "Intel Core i7-1360P",
    ram: 16,
    storage: 512,
    gpuBrand: "integrated",
    gpu: "Intel Iris Xe",
    screen: 13.4,
    price: 1499,
    availability: "in_stock",
    imageUrl: "/images/placeholder.svg",
    tags: ["dell", "premium", "ultrabook"],
    url: "#"
  },
  {
    name: "HP Spectre x360 14",
    brand: "HP",
    type: "laptop",
    cpuBrand: "intel",
    cpu: "Intel Core i7-1355U",
    ram: 16,
    storage: 1024,
    gpuBrand: "integrated",
    gpu: "Intel Iris Xe",
    screen: 13.5,
    price: 1599,
    availability: "preorder",
    inStock: false,
    imageUrl: "/images/placeholder.svg",
    tags: ["hp", "2-in-1", "touch"],
    url: "#"
  },
  {
    name: "Acer Nitro 5",
    brand: "Acer",
    description: "Budget gaming laptop with RTX graphics.",
    category: "gaming",
    type: "laptop",
    cpuBrand: "intel",
    cpu: "Intel Core i5-12500H",
    ram: 16,
    storage: 512,
    gpuBrand: "nvidia",
    gpu: "NVIDIA RTX 4050",
    screen: 15.6,
    price: 999,
    availability: "in_stock",
    rating: 4.1,
    popularity: 520,
    imageUrl: "/images/placeholder.svg",
    tags: ["acer", "gaming", "budget"],
    url: "#"
  },
  {
    name: "ASUS ROG Strix G16",
    brand: "ASUS",
    description: "High-end gaming laptop with powerful GPU.",
    category: "gaming",
    type: "laptop",
    cpuBrand: "intel",
    cpu: "Intel Core i9-13980HX",
    ram: 32,
    storage: 1024,
    gpuBrand: "nvidia",
    gpu: "NVIDIA RTX 4070",
    screen: 16,
    price: 2199,
    availability: "in_stock",
    rating: 4.7,
    popularity: 710,
    imageUrl: "/images/placeholder.svg",
    tags: ["asus", "gaming", "240hz"],
    url: "#"
  },
  {
    name: "MSI Katana 15",
    brand: "MSI",
    description: "Gaming laptop tuned for high FPS titles.",
    category: "gaming",
    type: "laptop",
    cpuBrand: "intel",
    cpu: "Intel Core i7-13620H",
    ram: 16,
    storage: 1024,
    gpuBrand: "nvidia",
    gpu: "NVIDIA RTX 4060",
    screen: 15.6,
    price: 1299,
    availability: "in_stock",
    rating: 4.4,
    popularity: 480,
    imageUrl: "/images/placeholder.svg",
    tags: ["msi", "gaming"],
    url: "#"
  },
  {
    name: "MacBook Air 13",
    brand: "Apple",
    type: "laptop",
    cpuBrand: "apple",
    cpu: "Apple M3",
    ram: 16,
    storage: 512,
    gpuBrand: "apple",
    gpu: "Apple GPU",
    screen: 13.6,
    price: 1299,
    availability: "in_stock",
    imageUrl: "/images/placeholder.svg",
    tags: ["macos", "portable"],
    url: "#"
  },
  {
    name: "Surface Laptop 5",
    brand: "Microsoft",
    type: "laptop",
    cpuBrand: "intel",
    cpu: "Intel Core i7-1255U",
    ram: 16,
    storage: 512,
    gpuBrand: "integrated",
    gpu: "Intel Iris Xe",
    screen: 15,
    price: 1399,
    availability: "in_stock",
    imageUrl: "/images/placeholder.svg",
    tags: ["microsoft", "premium"],
    url: "#"
  },
  {
    name: "Framework Laptop 13",
    brand: "Framework",
    type: "laptop",
    cpuBrand: "intel",
    cpu: "Intel Core i7-1360P",
    ram: 16,
    storage: 1000,
    gpuBrand: "integrated",
    gpu: "Intel Iris Xe",
    screen: 13.5,
    price: 1399,
    availability: "preorder",
    inStock: false,
    imageUrl: "/images/placeholder.svg",
    tags: ["framework", "repairable"],
    url: "#"
  },
  {
    name: "Beelink SER6",
    brand: "Beelink",
    type: "mini-pc",
    cpuBrand: "amd",
    cpu: "AMD Ryzen 7 7735HS",
    ram: 32,
    storage: 1024,
    gpuBrand: "integrated",
    gpu: "Radeon 680M",
    screen: 0,
    price: 649,
    availability: "in_stock",
    imageUrl: "/images/placeholder.svg",
    tags: ["mini", "amd"],
    url: "#"
  },
  {
    name: "Intel NUC 12",
    brand: "Intel",
    type: "mini-pc",
    cpuBrand: "intel",
    cpu: "Intel Core i7-1260P",
    ram: 16,
    storage: 512,
    gpuBrand: "integrated",
    gpu: "Intel Iris Xe",
    screen: 0,
    price: 699,
    availability: "in_stock",
    imageUrl: "/images/placeholder.svg",
    tags: ["mini", "intel"],
    url: "#"
  },
  {
    name: "Alienware Aurora R16",
    brand: "Dell",
    description: "Gaming desktop with RTX graphics and strong airflow.",
    category: "gaming",
    type: "desktop",
    cpuBrand: "intel",
    cpu: "Intel Core i7-13700F",
    ram: 32,
    storage: 1024,
    gpuBrand: "nvidia",
    gpu: "NVIDIA RTX 4070",
    screen: 0,
    price: 2199,
    availability: "in_stock",
    rating: 4.6,
    popularity: 590,
    imageUrl: "/images/placeholder.svg",
    tags: ["dell", "gaming"],
    url: "#"
  },
  {
    name: "HP Victus Tower",
    brand: "HP",
    description: "Gaming desktop with balanced performance for 1080p gaming.",
    category: "gaming",
    type: "desktop",
    cpuBrand: "amd",
    cpu: "AMD Ryzen 5 7600",
    ram: 16,
    storage: 1024,
    gpuBrand: "nvidia",
    gpu: "NVIDIA RTX 3060",
    screen: 0,
    price: 999,
    availability: "in_stock",
    rating: 4.0,
    popularity: 450,
    imageUrl: "/images/placeholder.svg",
    tags: ["hp", "gaming"],
    url: "#"
  },
  {
    name: "Apple iMac 24",
    brand: "Apple",
    type: "all-in-one",
    cpuBrand: "apple",
    cpu: "Apple M3",
    ram: 16,
    storage: 512,
    gpuBrand: "apple",
    gpu: "Apple GPU",
    screen: 23.5,
    price: 1799,
    availability: "in_stock",
    imageUrl: "/images/placeholder.svg",
    tags: ["macos", "aio"],
    url: "#"
  }
];

const main = async () => {
  await prisma.product.deleteMany();
  await prisma.product.createMany({ data: products, skipDuplicates: true });
};

main()
  .catch((error) => {
    console.error(error);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
